spring.application.name= connectify

logging.level.org.springframework.web.socket=DEBUG


# Public Railway endpoint (for local runs)
spring.datasource.url=${URL}

spring.datasource.username=root
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# logging configuration
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=WARN
logging.level.com.connectify.demo=TRACE

## CORS Config ##
cors.allowedOrigins=http://localhost:3000
cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS
cors.allowedHeaders=Authorization,Content-Type,token
